FROM chronos-beacon-chain:1.0 as chronos-beacon-chain-image

FROM alpine:latest

# Copy the binary
COPY --from=chronos-beacon-chain-image /usr/local/bin /usr/local/bin
RUN mkdir /chronos-beacon-chain

COPY artifacts/run_node_docker.sh /run_beacon_node.sh

COPY artifacts/network_keys/network_keys0 /chronos-beacon-chain/network_keys

EXPOSE 8551 4000 8080 12000 13000 3500 